### ISSUE TITLE
Création "d'un plan financeur" : Liste déroulante des modèles H2020 incomplète

### ISSUE THREAD

**Issue by lrassinoux** [OPIDoR/DMPOPIDoR#112]
**Expected behaviour:**
Quand on crée un plan (via la page de création de plan) et qu'on choisit comme financeur la Commission européenne, dans  la liste déroulante des modèles Commission européenne doivent s'afficher 3 modèles. 
Actuellement il manque dans cette liste déroulante CE le modèle **Horizon 2020 FAIR DMP (anglais)**. Donc faire apparaitre également dans cette liste le modèle **Horizon 2020 FAIR DMP (anglais)**

**Actual behaviour:**
Dans la page de création de plan, quand on choisit comme financeur la Commission européenne, seuls 2 modèles sont proposés dans la liste déroulante. Il manque le modèle **Horizon 2020 FAIR DMP (anglais)**. _L'explication serait que ce modèle étant le modèle par défaut pour l'application, il n'apparait pas dans la liste déroulante de la Commission Européenne._

![Capture-creation](https://user-images.githubusercontent.com/12936700/54207691-e8c08080-44da-11e9-8a88-feceda3b23dc.PNG)

**Steps to reproduce:**
Créer un plan, choisir commission européenne dans l'onglet financeur. Une liste de modèles Commission européenne s'affiche. Il manque le modèle Horizon 2020 FAIR DMP (anglais)

**Comment by benjaminfaure** [comment]
Résolu avec la V2.1.5
