### ISSUE TITLE
Message automatique partage : contenu (variables et message)

### ISSUE THREAD

**Issue by lrassinoux** [OPIDoR/DMPOPIDoR#113]
**Expected behaviour:**
Dans le message de partage reçu par la personne avec laquelle un utilisateur de DMP OPIDoR partage un plan, il faudrait : 
- **faire remonter** la phrase "Merci de ne pas répondre à ce mail. Si vous avez des questions ou si vous avez besoin d'aide, merci de nous contacter à %{helpdesk_email} ou consulter %{contact_us} **avant cordialement** 
- "activer" les **variables** pour faire apparaitre le mail et le contact.

**Actual behaviour:**
Quand un utilisateur reçoit une demande de partage, il reçoit le message ci-dessous en italique
Le message "merci de ne pas répondre..." est trop "loin" dans le message et les variables ne sont pas "activées" . voir ci-dessous 
__Untel_ vous a invité à contribuer à son plan de gestion de données sur DMP OPIDoR 
Cliquez ici pour accepter l'invitation, (ou copier https://dmp.opidor.fr/users/invitation/accept?invitation_token=R7vDq68MxC6GSej2i2MT dans votre navigateur). Si vous ne souhaitez pas accepter cette invitation, ignorez ce courriel. 
Cordialement 
L'équipe DMP OPIDoR 
Merci de ne pas répondre à ce mail. Si vous avez des questions ou si vous avez besoin d'aide, merci de nous contacter à %{helpdesk_email} ou consulter %{contact_us}_ 

**Steps to reproduce:**
Demander à un membre de l'équipe de partager un DMP avec soi pour recevoir un mail de partage.

**Comment by benjaminfaure** [comment]
Devrait être résolu :)
