### ISSUE TITLE
 Texte Banner organisme non enregistrable (VP et VI)

### ISSUE THREAD

**Issue by lrassinoux** [OPIDoR/DMPOPIDoR#117]
**Expected behaviour:**
Pouvoir enregistrer du texte dans la bannière de texte de l'organisme en VP et VI (VD OK)

**Actual behaviour:**
Je suis admin dans la VI, je rentre du texte dans la bannière de texte (text banner) de l'organisme dont je suis admin. J’enregistre et le texte disparaît

**Steps to reproduce:**
Je suis admin dans la VI, je rentre du texte dans la bannière de texte (text banner) de l'organisme dont je suis admin. J’enregistre et le texte disparaît

**Comment by benjaminfaure** [comment]
Ca devrait fonctionner sur la VD.
