### ISSUE TITLE
BUG Admin : Affichage des modèles

### ISSUE THREAD

**Issue by fcinist** [OPIDoR/DMPOPIDoR#157]
Interface Admin/Modèles (Vd, Vi et Vp) : 
- Affichage de toute une liste de modèles dans l'onglet "Vos modèles/Non publiés (0)", alors qu'il ne devrait en avoir aucun
- Idem dans l'onglet "Vos modèles/Publié (0)
Il n'est cependant pas possible de modifier ces modèles.

**Comment by benjaminfaure** [comment]
Résolu avec la V2.2.0
