### ISSUE TITLE
(VI) Titre obligatoire : obligation non effective

### ISSUE THREAD

**Issue by lrassinoux** [OPIDoR/DMPOPIDoR#161]
En VI 2.2.0
A la création de plan le titre est obligatoire.
Or, j'arrive à créer un plan sans mettre de titre (j'ai alors un titre par défaut (Laurent's plan)).

Rendre effective  l'obligation de titre :)

**Comment by benjaminfaure** [comment]
Apparemment c'est voulu qu'il ne soit pas obligatoire, j'ai retiré l'étoile indiquant qu"il est obligatoire :)
