### ISSUE TITLE
(VD et VI) Visibilité Administrateur d'un DMP

### ISSUE THREAD

**Issue by fcinist** [OPIDoR/DMPOPIDoR#163]
Un DMP est en visibilité "Administrateur".
Interface Admin/Plans : affichage du DMP dans le tableau de bord Admin. Par contre, impossibilité d'accéder au DMP (remplissage 0, 50 et 100%).
Attendu : accéder au DMP à partir du tableau de bord Admin (interface Admin/Plans)

**Comment by benjaminfaure** [comment]
Résolu sur la VD, sera résolu en VI quand on redéploiera une nouvelle version.
