### ISSUE TITLE
VI changement de visibilité  (50% toujours effectifs)

### ISSUE THREAD

**Issue by lrassinoux** [OPIDoR/DMPOPIDoR#168]
Dans la VI, la "barrière" des 50 % pour changer la visibilité d'un DMP devait être changée. La mention "Vous devez avoir répondu à au moins 50% des questions afin d'activer l’une de ces options" n'apparait plus ce quiest bien. Mais il n'est pas possible de changer la visibilité pour autant quand on a rempli qu'une petite partie de son dmp

**Comment by lrassinoux** [comment]
Je viens de remarquer que ça fonctionnait. Je peux changer la visibilité de mon plan même si je n'ai pas rempli la moitié de mon plan.

**Comment by benjaminfaure** [comment]
Résolu sur la VI et VP
