### ISSUE TITLE
Problème d'affichage/Page Créer un plan

### ISSUE THREAD

**Issue by abInist** [OPIDoR/DMPOPIDoR#17]
Please complete the following fields as applicable:

**Expected behaviour:**

**Actual behaviour:**
Quand je coche  aucun financeur ou mon organisme n'est pas dans la liste, j'obtiens ça:
![image](https://user-images.githubusercontent.com/36660986/36417636-c2404b4e-162c-11e8-8791-6d3edd3e1b4d.png)
La barre fait la largeurde l'écran.
De plus, elle n'est pas alignée avec le texte

**Steps to reproduce:**
Sur la page Créer un nouveau plan

**Comment by Sudiukil** [comment]
C'est résolu mais il est probable que ce genre de soucis d'affichage puisse être retrouvé sur d'autres formulaires, à vérifier et à corriger au cas par cas.
