### ISSUE TITLE
(VD, VI, VP) - Mise en forme des exports en docx

### ISSUE THREAD

**Issue by fcinist** [OPIDoR/DMPOPIDoR#173]
Remplacer les puces actuelles (symbole euros barrés) dans les exports en docx

**Comment by benjaminfaure** [comment]
Fixé pour la liste des produits de recherche et les questions à choix multiples. 

Je ne pense pas qu'on puisse corriger ce souci pour les puces insérées dans les éditeurs, à moins de retirer la possibilité d'en ajouter.
