### ISSUE TITLE
Amélioration des exports "Produits de recherche" en docx et PDF

### ISSUE THREAD

**Issue by fcinist** [OPIDoR/DMPOPIDoR#174]
A l’export, si on ne coche pas "Page de renseignements sur le projet", la liste des produits de recherche n’est pas affichée (avec leur type).
Prévoir une case à cocher dans les "Eléments optionnels du plan" pour exporter ou non le contenu de l’onglet "Produits de recherche"

**Comment by benjaminfaure** [comment]
Duplication de #155
