### ISSUE TITLE
Erreur d'affichage colonne Prénom dans Liste utilisateurs/phase administrateur 

### ISSUE THREAD

**Issue by abInist** [OPIDoR/DMPOPIDoR#18]
Please complete the following fields as applicable:

**Expected behaviour:**
Liste de noms et prénoms dans la colonne Name sur VP : 
![image](https://user-images.githubusercontent.com/36660986/36420219-9631e5d2-1634-11e8-9dd6-059d52da3b03.png)

**Actual behaviour:**
Affichage des adresses mail dans la colonne Prénom (traduction à revoir)  sur VD
![image](https://user-images.githubusercontent.com/36660986/36420022-f139f51a-1633-11e8-9127-419df21261a8.png)
Remarque: sur DMPonline-test, j'ai le même soucis

**Steps to reproduce:**
Se connecter en tant qu'administrateur/ onglet Users

**Comment by Sudiukil** [comment]
Réglé, les noms apparaissent maintenant correctement. Le mail peut continuer à s'afficher à la place du nom si le nom et le prénom de l'utilisateur sont absents, c'est voulu.
