### ISSUE TITLE
Rajouter IGSN comme "Liste les standards de métadonnées/données utilisés "

### ISSUE THREAD

**Issue by Cecilepignol** [OPIDoR/DMPOPIDoR#197]
Please complete the following fields as applicable:

https://www.igsn.org/

**Expected behaviour:**

**Actual behaviour:**

**Steps to reproduce:**

**Comment by JacquemotMC** [comment]
Merci pour votre contribution. Nous allons l'ajouter. Notre première liste de standards est basée sur le catalogue de standards de métadonnées mais nous envisageons de nous baser aussi (ou à la place si cela s'avérait plus pertinent)) sur celle de FAIRsharing.
