### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by LoicSan** [OPIDoR/DMPOPIDoR#207]
Bonjour,

j'ai réussi à créer l'image docker à partir de votre Dockerfile, moyennant quelques adaptations sur la version de ruby, la version de phusion/passenger-ruby et le bundler associé (erreurs sinon).
Par contre, une fois obtenu, je n'arrive pas à lancer l'image pour instancier le conteneur.

J'obtiens ce type d'erreur :
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "rails": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled

A la fin du Dockerfile, on a un CMD["rails"].
Je me demande si ce n'est ce qui pose problème ?

J'ai ajouté le chemin au path ( ENV PATH=$PATH:/usr/local/bin ) mais sans plus de succès... 

Merci par avance de votre éclairage sur l'instanciation avec Docker du projet.
Cordialement.

**Comment by benjaminfaure** [comment]
Bonjour,

La dernière ligne du Dockerfile `CMD["rails.sh"]` fait référence au fichier rails.sh qui se situe au même niveau que le Dockerfile.

Ce Dockerfile avait été utilisé en interne dans le cadre d'un déploiement (avec docker compose) par Integration Continue avec Jenkins. Il se peut qu'il manque des variables d'environnement pour bien faire fonctionner l'application.

A noter que le code présent sur la branche principale est compatible avec Rails 4.2 & Ruby 2.4. Si vous avez utilisé les dernières versions de l'imagine Passenger, Ruby 2.4 n'est plus disponible car en fin de vie.
Je travaille actuellement à migrer le code vers la dernière version du fork principal qui utilise Rails 5.2 & Ruby 2.6

**Comment by LoicSan** [comment]
Oui, pour info, j'ai modifié les lignes ci-dessous du Dockerfile pour créer l'image.
Si le code n'est pas compatible avec Ruby 2.6, cela explique peut-être la difficulté à lancer l'image ensuite.
Je vais voir pour essayer de l'installer directement à partir des sources du coup.
Merci pour votre retour.


FROM phusion/passenger-ruby26:2.0.0
....
# Setting some env vars
ENV HOME=/root \
    PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 \
    LANGUAGE=fr_FR.UTF-8 \
    LANG=fr_FR.UTF-8 \
    LC_ALL=fr_FR.UTF-8 \
    RUBY_VERSION=2.6.8
....
+ ajout variables d'environnement du proxy
ENV http_proxy...
ENV https_proxy...

....
RUN bash -lc 'rvm install ruby-2.6.8'
RUN bash -lc 'rvm --default use ruby-2.6.8'
....
# Installing Ruby and Node dependencies
RUN echo $RUBY_VERSION > .ruby-version \
    && gem install bundler -v 2.0.0.pre.3 \
    && echo 'gem "tzinfo-data"' >> Gemfile \
    # && bundle install --without mysql puma thin
    && bundle install --without mysql
RUN yarn

**Comment by LoicSan** [comment]
J'ai par ailleurs sans doute oublié une étape en relisant le Readme.md.
Avant de lancer le docker build, il faut créer un fichier database.yml sous le répertoire config j'imagine ?
Où est renseignée la variable  ENV["DB_ADAPTER"] ? dans le dockerfile ?
La commande "rake db:create" est prévue dans rails.sh par contre.

**Comment by benjaminfaure** [comment]
Je pense que le problème est résolu, je clos cette issue
