### ISSUE TITLE
Export de DMP (parfois des problèmes avec Google Chrome)

### ISSUE THREAD

**Issue by lrassinoux** [OPIDoR/DMPOPIDoR#210]
Quelques utilisateurs ont eu des soucis de téléchargement de leur DMP 

Après test, on s'est rendu compte que le téléchargement était défectueux -pour **certains** DMP- avec le navigateur Google Chrome.
Par contre ces mêmes DMP ont pu être téléchargés avec Firefox.

Attendu : identifier le problème avec Google Chrome et éviter des éventuels problèmes de téléchargement de DMP avec Google Chrome.
J'ai rajouté la copie d'écran de l'erreur 
![Capture](https://user-images.githubusercontent.com/12936700/154467972-da460e5e-9e77-4692-b324-43d4f477da0a.PNG)

**Comment by benjaminfaure** [comment]
Ce problème a été résolu dans la V3.1.0
