### ISSUE TITLE
How to install DMP OPIDoR

### ISSUE THREAD

**Issue by froggypaule** [OPIDoR/DMPOPIDoR#212]
Bonjour ! j'ai besoin que l'on me file un coup de main pour installer DMP OPIDoR (master branch). Pour l'instant mon but c'est d'explorer la structure de la db. I got stuck in the README file at the 

    Configurer config/database.yml avec une base de donnée valide
    Créer la base et executer les migrations :
    rake db:create

to end up with 
"FATAL:  Peer authentication failed for user "postgres"

Je n'ai jamais travaillé avec ruby sur rails etc... 

Bref : quelle config pour la db va me permettre de la créer ? j'ai utilisé le fichier database.yml.sample_ci comme example....
Merci !

**Comment by benjaminfaure** [comment]
Bonjour,

Si le besoin est de consulter la structure de la base, il suffit de consulter ce fichier https://github.com/OPIDoR/DMPOPIDoR/blob/dmpopidor-master/db/schema.rb
Il contient la liste des tables et les liens entre les tables.

**Comment by froggypaule** [comment]
oui j'ai bien vu, mais j'aimerai la créer pour de besoins de visualisation, une couche qui s'ajouterait à la db SQL. Pour avoir une compréhension 'immédiate' des interactions entre les classes/tables.`

**Comment by benjaminfaure** [comment]
L'installation est désormais possible avec Docker.
Voir README : https://github.com/OPIDoR/DMPOPIDoR/blob/main/README.md
