### ISSUE TITLE
Latest release broke all public DMPs hyperlinks

### ISSUE THREAD

**Issue by Enro** [OPIDoR/DMPOPIDoR#218]
**Expected behaviour:**
Public DMPs used to be accessible through URLs having the syntax https://dmp.opidor.fr/plans/8490/export.pdf

**Actual behaviour:**
 Since the latest release, the syntax is now https://dmp.opidor.fr/plans/8490/export.pdf?export[question_headings]=true (note the added parameter that is passed after *export.pdf*). All links to **public** DMPs are thus broken.

Could you revert to the former hyperlink syntax, or at least make the new release compatible with the former URL syntax?

**Comment by benjaminfaure** [comment]
Hello @Enro
Thank you for your feedback.

With our latest major release, we migrated from Rails 4 to 5 which brought a lot a changes in the code and I might have missed some changes coming from the main fork.  
Seems like they added some mandatory parameters to the plan export process. Without it, the pdf can't be generated. 
I will investigated this problem and try to solve it in a coming release.

**Comment by benjaminfaure** [comment]
Hello, this issue has been resolved in the V3.2.0 that is now in deployed in production.

**Comment by Enro** [comment]
Thank you very much!
