### ISSUE TITLE
DMP structuré : export des libellés statiques en anglais

### ISSUE THREAD

**Issue by equinton** [OPIDoR/DMPOPIDoR#219]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

**Expected behaviour:**

À partir du DMP structuré Science Europe, nous n'avons pas réussi à exporter le plan avec les libellés statiques en anglais. 

Nous avons besoin de rédiger des plans en anglais, et les intitulés des questions ou des rubriques doivent pouvoir également être exportés en anglais (pdf, html ou docx), notamment pour une relecture par nos partenaires européens.

**Actual behaviour:**

**Steps to reproduce:**

**Comment by lrassinoux** [comment]
Bonjour, 
Le modèle de DMP Science Europe structuré est également disponible en version anglaise ("Science Europe: structured template"). 
Pour créer un DMP avec cette version anglaise (qui vous permettra d'avoir les intitulés de questions et sections en anglais), dans la page de création d'un DMP, vous devez renseigner "Science Europe" comme organisme et choisir "Science Europe: structured template" comme modèle.  Voir la copie 1 ci-après .  

Nous vous conseillons également de changer la langue de l'interface (voir copie 2). Ce conseil vaut également pour vos partenaires européens qui utiliseraient DMP OPIDoR (ils auraient ainsi les intitulés de fonctionnalités, menu etc de l'interface en anglais, ainsi que les éventuels messages de notifications de partage, commentaires...)

**Copie 1 choix du modèle**
 ![Capture1-modele](https://user-images.githubusercontent.com/12936700/173814083-e06ab28c-2fd4-43ec-8434-1bf0dd8e1c5f.PNG)  

**Copie 2 : changement de la langue de l'interface** 
![Capture2-interface-anglaise](https://user-images.githubusercontent.com/12936700/173815010-1e7ff398-b918-46c0-8b6f-ec2304da05b8.PNG)

**Comment by equinton** [comment]
ok, merci !
Je diffuse l'info à ceux qui étaient intéressés.
Cordialement,
Éric Q.
