### ISSUE TITLE
Question: how to API

### ISSUE THREAD

**Issue by froggypaule** [OPIDoR/DMPOPIDoR#220]
This a very simple question: 
- if you could provide me with the minimum info required for me to import a json DMP into DMPOPIDoR via API: syntax, required fields, etc.
- also, some info regarding the structure of the DMP json file would be very helpful.

Thanks!

**Comment by benjaminfaure** [comment]
Hello, 
There's a documentation on how to use the API on the wiki : https://github.com/OPIDoR/DMPOPIDoR/wiki/API-DMP-OPIDoR

There should be some example on how to use the API.

Moreover, we're currently working on integrating a SwaggerUI in DMP OPIDoR which should make using the API a bit more user friendly

**Comment by froggypaule** [comment]
Thanks for this. I'll first try to successfully import a DMP.
