### ISSUE TITLE
Importing DMP in json format into DMP OPIDoR 

### ISSUE THREAD

**Issue by froggypaule** [OPIDoR/DMPOPIDoR#221]
Please complete the following fields as applicable:

**using the online DMP OPIDoR importing fonction https://dmp.opidor.fr/plans/import**

**Expected behaviour:**
Seeing json files (ie files  with json suffixes), as here 
![Screenshot from 2022-09-08 14-58-59](https://user-images.githubusercontent.com/47455219/189128037-8b1ae113-67c2-4854-9d5c-50f17696411a.png)

**Actual behaviour:**
Can only see one file, as here 
![Screenshot from 2022-09-08 15-00-01](https://user-images.githubusercontent.com/47455219/189128252-71ef2748-51be-4d34-a9bc-9881c82307cf.png)

Thanks! I am a bit confused...

**Comment by benjaminfaure** [comment]
If I'm correct, the displayed window looks like the latest Ubuntu version (2204). I migrated this week and I noticed this change : 
It displays all the available files in the user HOME folder, it no longer displays one folder like Windows.

Seems like it's more an Ubuntu problem than a DMP OPIDoR problem :)

**Comment by froggypaule** [comment]
yes, correct: we are in 22.04. 
You are quite right, thanks!  now I remember: indeed, 22.04 has stricter access control (had the same issue with firefox).

I'll have a look, and I hope to post the solution here.

**Comment by froggypaule** [comment]
OK: it is partially related to https://bugs.launchpad.net/snapd/+bug/1972762. In essence snap may not access directories other than /home (firefox is now distributed by snap, as an example).

 But in my case, I had access to home, it is simply that the interface allowing file upload shows quite bizarrely: after type $HOME in the search bar, one arrives under home; it is simply not intuitive....
