### ISSUE TITLE
Numérotation du modèle ANR structuré

### ISSUE THREAD

**Issue by Enro** [OPIDoR/DMPOPIDoR#326]
Bonjour,

sur la nouvelle version DMP OPIDoR V4, les rubriques du modèle ANR structuré sont mal numérotées. Je m'explique : après la rubrique "3. Exigences légales et éthiques, code de conduite" viennent les rubriques "**4. 4.** Traitement et analyse des données" puis "**5. 5.** Stockage et sauvegarde des données pendant le processus de recherche" puis "**6. 6.** Partage des données et conservation à long terme".

Il doit y avoir un bug qui doublonne le numéro sur ces trois dernières rubriques.

Bien cordialement

**Comment by lrassinoux** [comment]
Bonjour, Vous avez dû créer votre PGD "en même temps" que nous faisions les modifs de numérotation. Pour explication : la nouvelle interface V4 "prévoit" une numérotation automatique des  sections et questions des modèles de type structuré. Avant la mise en production de la V4, dans la V3 nous faisions manuellement la numérotation des modèles structurés. D'où une double numérotation que nous avons dû corriger manuellement. A un moment on a publié nos modifs et on s'est rendu compte qu'il restait une double numérotation..Bref :) le problème est réglé dans la numérotation des sections / questions. Merci encore pour vos retours

**Comment by Enro** [comment]
C'est compris, merci à vous pour les explications @lrassinoux !
