### ISSUE TITLE
Bug sélecteur PGD structuré

### ISSUE THREAD

**Issue by Enro** [OPIDoR/DMPOPIDoR#328]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

DMP OPIDoR V4

**Expected behaviour:**

Une option qui est supprimée puis enregistrée ne s'affiche plus dans le PGD.

**Actual behaviour:**

L'option revient et ne peut pas être supprimée : cf. capture vidéo https://mediapod.u-bordeaux.fr/video/43078-bug-selecteur-dmp-opidor/ (mot de passe DMPOPIDoR)

**Comment by lrassinoux** [comment]
Bonjour et merci beaucoup pour ce retour/bug transmis aux développeurs pour correction. A bientôt pour vos donner des nouvelles

**Comment by lrassinoux** [comment]
Bonjour, une nouvelle version de DMP OPIDoR (V4.0.2) a été mise en ligne le 21/5/24 contenant corrections et améliorations dont la correction du bug que vous aviez détecté . Voir la release de cette nouvelle version [https://github.com/OPIDoR/DMPOPIDoR/releases/tag/V4.0.2](url)

**Comment by Enro** [comment]
Parfait, je vous remercie !
