### ISSUE TITLE
Coquille dans les types de produits de recherche

### ISSUE THREAD

**Issue by Enro** [OPIDoR/DMPOPIDoR#329]
Dans DMP OPIDoR V4, la liste à choix des produits de recherche contient "Resource interactive" auquel il manque un "s" :-)

**Comment by lrassinoux** [comment]
Bonjour et merci pour cette remarque. La correction vient d'être faite :). Encore merci pour votre collaboration.

**Comment by Enro** [comment]
Merci beaucoup à vous !
