### ISSUE TITLE
Francisation DMP -> PGD

### ISSUE THREAD

**Issue by Enro** [OPIDoR/DMPOPIDoR#331]
Est-il possible de franciser DMP en PGD dans les textes et l'interface de DMP OPIDoR ? Je pense aux rubriques "Modèles de DMP" et "DMP publics"... alors que d'autres rubriques s'appellent "Mes plans", "Exemples de plans de gestion des données"...

J'ai du mal à voir l'intérêt de faire coexister ces deux termes, d'autant que l'acronyme PGD a bien pris dans nos communautés. Merci !

**Comment by lrassinoux** [comment]
Bonjour et merci pour votre retour. Je transmettrai votre suggestion à l'équipe.

**Comment by lrassinoux** [comment]
Bonjour, la francisation du terme DMP en PGD a été effectuée. Merci encore pour ce retour et bonne après-midi.

**Comment by Enro** [comment]
Super, merci beaucoup !
