### ISSUE TITLE
Interface : puces non prises en compte

### ISSUE THREAD

**Issue by par4dise** [OPIDoR/DMPOPIDoR#35]
Lors de l'ajout de puces dans les zones "Description", "Guidance" ou encore "Example of answer" en mode édition, elles n'apparaissent pas sur l'interface utilisateur.

**Mode admin**
<img width="682" alt="capture d ecran 2018-03-12 a 12 16 44" src="https://user-images.githubusercontent.com/3480636/37280847-49ffc2e0-25ef-11e8-84de-ba86df95c8cd.png">

**Mode utilisateur**
<img width="913" alt="capture d ecran 2018-03-12 a 12 17 42" src="https://user-images.githubusercontent.com/3480636/37280881-657543d8-25ef-11e8-96eb-c750bb03de74.png">

**Comment by Sudiukil** [comment]
Le problème est connu et déjà en partie réglé, la plupart des zones d'éditions de l'appli sont concernées.

Edit 1 : J'attends que mes changements récents soient fusionnés et j'enquête sur un moyen de régler le soucis sur l'intégralité de l'appli

**Comment by benjaminfaure** [comment]
Merci pour votre message, comme je le précisais par mail ce dépot concerne le code basé sur DMPRoadmap qui sera déployé en production dans les prochaines semaines. 
Une fois le déploiement effectué, n'hésitez pas à poster des issues si nécessaire :)
