### ISSUE TITLE
Partage de DMP avec un collaborateur 

### ISSUE THREAD

**Issue by fcinist** [OPIDoR/DMPOPIDoR#40]
Please complete the following fields as applicable:
 
Lorsqu'un utilisateur fait une erreur dans le mail d'un collaborateur, info-opidor@inist.fr reçoit le message suivant 
![image](https://user-images.githubusercontent.com/36701738/37412569-72ca1fec-27a5-11e8-86c0-9e7e583c4093.png)

Le message actuel est ok mais on ne connait pas le nom de l'utilisateur qui a fait une demande de partage.
Ne serait-il pas plus intéressant que celui qui a fait la demande de partage reçoive aussi ce message d'alerte ?

**Comment by benjaminfaure** [comment]
Le souci avec ce message c'est qu'il est géré par le serveur de mail donc indépendant de nous. Je ne pense pas qu'on puisse l'améliorer. Il est envoyé au mail expéditeur donc info-opidor.

**Comment by benjaminfaure** [comment]
Je viens de faire une modif pour intégrer le nom de l'utilisateur qui partage dans le titre du mail :) 
Ce souci devrait être réglé !
