### ISSUE TITLE
Footer interface VD : A propos non accessible + ouverture des pages (souhaitable vers une autre page)

### ISSUE THREAD

**Issue by lrassinoux** [OPIDoR/DMPOPIDoR#58]
Au niveau du footer de l'interface VD
- Remarque ergonomique : Il serait bon que les pages des liens s'ouvrent vers une autre page en particulier pour 2016-2018 Inist, Github, Twitter... qui sont des liens externes. Par contre c'est bon pour CNRS et Roadmap qui s'ouvrent bien vers une autre page.

- Le lien vers la page d'A propos ne fonctionne pas ça rame et on aboutit à

![image](https://user-images.githubusercontent.com/12936700/39692435-262351a2-51e1-11e8-8f3c-94b264ae0b91.png)

**Comment by benjaminfaure** [comment]
J'ai résolu le souci des liens ne s'ouvrant pas dans un nouvel onglet.
Concernant le deuxième problème, je n'avais pas retiré l'appel aux flux RSS venant du blog DCC. Ca fonctionne sur ma machine, mais sur la VD ça déconne. Ca sera résolu à la prochaine version :)

**Comment by benjaminfaure** [comment]
Le souci est réglé je clos :)
